export {default as Login} from './Login';
export {default as Home} from './Home';
export {default as Order} from './Order';
export {default as Product} from './Product';
export {default as Import} from './Import';
export {default as UserControl} from './UserControl';
export {default as Discounts } from './Discounts';
export { default as Statistic} from './Statistic';
export {default as Vendors} from './Vendors';
export {default as Sale} from './Sale';
export {default as Categoty} from './Categoty';
